name: AuthenticateGHCR
description: 'Authenticates against GHCR'
inputs:
    actor:
      description: 'Github Actor'
      required: true
    secret:
      description: 'Github Token Secret'
      required: true
runs:
  using: "composite"
  steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2
      with:
        registry: ghcr.io
        username: ${{ inputs.actor }}
        password: ${{ inputs.secret }}

