name: InstallKarpenter
description: 'Installs Go Downloads and installs Karpenter Dependencies'
inputs:
  account_id:
    description: "Account ID to access AWS"
    required: true
  role:
    description: "Role to access AWS"
    required: true
  region:
    description: "Region to access AWS"
    required: true
  ecr_account_id:
    description: "Account ID for the ECR repo"
    required: true
  ecr_region:
    description: "Region for the ECR repo"
    required: true
  cluster_name:
    description: 'Name of the cluster to be launched by eksctl'
    required: true
  git_ref:
    description: "The git commit, tag, or branch to check out. Requires a corresponding Karpenter snapshot release"
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
    with:
      ref: ${{ inputs.git_ref }}
  - uses: ./.github/actions/e2e/install-helm
    with:
      version: v3.12.3 # Pinned to this version since v3.13.0 has issues with anonymous pulls: https://github.com/helm/helm/issues/12423
  - name: create karpenter namespace
    shell: bash
    run: |
      kubectl create ns karpenter || true
      kubectl label ns karpenter scrape=enabled --overwrite=true
      kubectl label ns karpenter pod-security.kubernetes.io/enforce=restricted --overwrite=true
  - name: login to ecr via docker
    uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3
    with:
      registry: ${{ inputs.ecr_account_id }}.dkr.ecr.${{ inputs.ecr_region }}.amazonaws.com
      logout: true
  - name: install-karpenter
    shell: bash
    run: |
      aws eks update-kubeconfig --name "${{ inputs.cluster_name }}"
        helm upgrade --install karpenter oci://${{ inputs.ecr_account_id }}.dkr.ecr.${{ inputs.ecr_region }}.amazonaws.com/karpenter/snapshot/karpenter \
        -n karpenter \
        --version "v0-$(git rev-parse HEAD)" \
        --set serviceAccount.annotations."eks\.amazonaws\.com/role-arn"="arn:aws:iam::${{ inputs.account_id }}:role/karpenter-irsa-${{ inputs.cluster_name }}" \
        --set settings.clusterName="${{ inputs.cluster_name }}" \
        --set settings.aws.defaultInstanceProfile="KarpenterNodeInstanceProfile-${{ inputs.cluster_name }}" \
        --set settings.interruptionQueue="${{ inputs.cluster_name }}" \
        --set controller.resources.requests.cpu=3 \
        --set controller.resources.requests.memory=3Gi \
        --set controller.resources.limits.cpu=3 \
        --set controller.resources.limits.memory=3Gi \
        --set serviceMonitor.enabled=true \
        --set serviceMonitor.additionalLabels.scrape=enabled \
        --set "serviceMonitor.endpointConfig.relabelings[0].targetLabel=clusterName" \
        --set "serviceMonitor.endpointConfig.relabelings[0].replacement=${{ inputs.cluster_name }}" \
        --set "serviceMonitor.endpointConfig.relabelings[1].targetLabel=gitRef" \
        --set "serviceMonitor.endpointConfig.relabelings[1].replacement=$(git rev-parse HEAD)" \
        --set "serviceMonitor.endpointConfig.relabelings[2].targetLabel=mostRecentTag" \
        --set "serviceMonitor.endpointConfig.relabelings[2].replacement=$(git describe --abbrev=0 --tags)" \
        --set "serviceMonitor.endpointConfig.relabelings[3].targetLabel=commitsAfterTag" \
        --set "serviceMonitor.endpointConfig.relabelings[3].replacement=\"$(git describe --tags | cut -d '-' -f 2)\"" \
        --wait
  - name: diff-karpenter
    shell: bash
    run: |
      helm diff upgrade --namespace karpenter \
        karpenter oci://${{ inputs.ecr_account_id }}.dkr.ecr.${{ inputs.ecr_region }}.amazonaws.com/karpenter/snapshot/karpenter \
        --version v0-$(git rev-parse HEAD) \
        --reuse-values --three-way-merge --detailed-exitcode
