name: PublishTestTools
on:
  push:
    branches:
      - 'main'
      - 'release-v*'
    paths:
      - test/Dockerfile
      - test/push-docker.sh
  schedule:
    - cron: '0 13 * * MON'
permissions:
  id-token: write # aws-actions/configure-aws-credentials@v4.0.1
jobs:
  publish-tools:
    if: github.repository == 'aws/karpenter'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/install-deps
      - uses: aws-actions/configure-aws-credentials@010d0da01d0b5a38af31e9c3470dbfdabdecca3a # v4.0.1
        with:
          role-to-assume: 'arn:aws:iam::${{ vars.ECR_ACCOUNT_ID }}:role/${{ vars.ECR_SNAPSHOT_ROLE_NAME }}'
          aws-region: ${{ vars.ECR_REGION }}
      - run: ./push-docker.sh
        working-directory: ./test
