name: StaleBot
on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'
jobs:
  StaleBot:
    runs-on: ubuntu-latest
    permissions:
<<<<<<< HEAD
      issues: write
      discussions: write
      pull-requests: write
    if: github.repository == 'aws/karpenter-core'
=======
      issues: write # actions/stale@v8.0.0
      pull-requests: write # actions/stale@v8.0.0
<<<<<<< HEAD
    if: github.repository == 'aws/karpenter'
>>>>>>> 1db74f402628818c1f6ead391cc039d2834e7e13
=======
    if: github.repository == 'aws/karpenter-provider-aws'
>>>>>>> 6ebba50ce424ccd5e33b3c84b4f10a8e78d54539
    name: Stale issue bot
    steps:
      - uses: actions/stale@28ca1036281a5e5922ead5184a1bbf96e5fc984e # v9.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue has been inactive for 14 days. StaleBot will close this stale issue after 14 more days of inactivity.'
          exempt-issue-labels: 'bug,chore,feature,documentation,testing,operational-excellence,automation,roadmap'
          stale-issue-label: 'lifecycle/stale'
          close-issue-label: 'lifecycle/closed'
          stale-pr-message: 'This PR has been inactive for 14 days. StaleBot will close this stale PR after 14 more days of inactivity.'
          exempt-pr-labels: 'blocked,needs-review,needs-design'
          stale-pr-label: 'lifecycle/stale'
          close-pr-label: 'lifecycle/closed'
          days-before-stale: 14
          days-before-close: 14
          operations-per-run: 300
